### ISSUE TITLE
Issue with ``overview`` handler?

### ISSUE THREAD

**Issue by TimKam** [jacamo-lang/jacamo-rest#46]
I just noticed that the ``overview`` handler sometimes returns a ``500`` error.
In [this PR](https://github.com/jacamo-lang/jacamo-rest/pull/45), I added a handler test for the ``overview`` handler that checks if a simple GET request works. It seems that this is not always the case, depending on the exact order in which the tests are executed.
First I thought it was a problem with the test, but I checked and it seems to be a problem with the handler. I assume the handler should never return a ``500`` for the overview GET request and it must be something in the server's state that changes throughout the execution of the tests and then makes the server catch an exception and returning an error when the overview is requested.

**Edit:** The error occurs when first deleting an agent and then sending a GET against the overview handler.

**Comment by cleberjamaral** [comment]
Indeed, overview was getting an error after deleting a 'local' agent. It had a test that did not remove from WP (white pages provided by zookeeper) when agent was local (only remote agents were removed). All endpoints are based on the list of the WP to return agents. In case of /agents it was not giving error because it only get the name from the WP, not other details from the agent. I changed the delete method to always remove the agent from the WP which for me sounds to be the right thing to do.
